# Generated by Django 4.2.7 on 2023-11-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='anaghaa', upload_to='pics'),
            preserve_default=False,
        ),
    ]
